### ISSUE TITLE
Are you planning on pushing this to nuget.org?

### ISSUE THREAD

**Issue by gep13** [aabenoja/Cake.Parallel#1]
I wasn't aware of this module, as I hadn't seen it pushed to nuget.org.  Are you planning on doing this?

**Comment by aabenoja** [comment]
Sorry for the long delay in response. I hadn't considered it before due to the nature of the project, but I'll add it to my todo list.

**Comment by gep13** [comment]
@aabenoja can you elaborate on `nature of the project`?  What exactly does this mean?

**Comment by aabenoja** [comment]
This project is a very imperfect. It is a buggy module written before cake's module system had any documentation on it by delving straight into cake's source code. I didn't even know that pulling down cake modules via nuget worked, so that's certainly part of it. More importantly, the parallelization provided is very much a hack that overrides the existing cake engine to teach cake how to spawn a thread for each task in your dependency graph. This isn't exactly desirable in all cases, as discussed [here](https://github.com/cake-build/cake/issues/156#issuecomment-298039838).

That isn't to say it is bad to use this module in your ecosystem. When we first introduced this into my company's pipeline it cut down our build time from 10 minutes to 5. For us the pros outweighed the cons.

**Comment by aabenoja** [comment]
@gep13 Is has been pushed. Verified that it works with the `Cake.Paket` module and customized `build.ps1` script from that blog post a while back, but I'm still not quite sure how to verify with the default bootstrapper. I'm going to close the issue for now, though, since it's now public.

https://www.nuget.org/packages/Cake.Parallel.Module/

**Comment by gep13** [comment]
@aabenoja that is great news! Thank you for doing this!
