### ISSUE TITLE
Cake.Parallel does not successfully install when using bootstrap

### ISSUE THREAD

**Issue by stephan7878** [aabenoja/Cake.Parallel#4]
**What You Are Seeing?**
Cake.Parallel module does not install successfully when using the bootstrap argument.

**What is Expected?**
Module should install successfully.

**What version of Cake are you using?**
0.25.0

**Are you running on a 32 or 64 bit system?**
64

**What environment are you running on? Windows? Linux? Mac?**
Windows

**Are you running on a CI Server? If so, which one?**
Yes. TFBuid

**How Did You Get This To Happen? (Steps to Reproduce)**

In build.cake added the module Preprocessor Directives
```
#module "nuget:?package=Cake.Parallel.Module&prerelease=true"
```

Using the bootstrap parameter to install the module fails with an error
```
build.ps1 --bootstrap
```

**Output Log**

2018-02-21T14:13:55.1024598Z Preparing to run build script...
2018-02-21T14:13:57.6963592Z Running build script...
2018-02-21T14:14:11.0563213Z Error: Failed to install module 'Cake.Parallel.Module'.
2018-02-21T14:14:11.1813253Z ##[error]Process completed with exit code 1.

**Comment by aabenoja** [comment]
Is that with the verbose flag enabled?

**Comment by stephan7878** [comment]
Sorry, below with diagnostic verbosity

```
PS C:\Repos\Cake> .\build.ps1 --bootstrap -Verbosity Diagnostic
Preparing to run build script...
Running build script...
Verifying assembly 'Cake.Parallel.Module, Version=0.20.0.0, Culture=neutral, PublicKeyToken=null'.
Registering module Cake.Parallel.Module.ParallelCakeModule...
NuGet.config not found.
Analyzing C:/Repos/Cake/build.cake...
Installing modules...
  GET https://api.nuget.org/v3/registration3-gz-semver2/cake.parallel.module/index.json
  OK https://api.nuget.org/v3/registration3-gz-semver2/cake.parallel.module/index.json 1129ms
Found package 'Cake.Parallel.Module 0.20.0' in 'C:/Repos/Cake/tools/Modules'.
Package Cake.Parallel.Module.0.20.0 has already been installed.
Successfully installed 'Cake.Parallel.Module 0.20.0' to C:/Repos/Cake/tools/Modules
Executing nuget actions took 29.49 ms
Error: Cake.Core.CakeException: Failed to install module 'Cake.Parallel.Module'.
   at Cake.Core.Scripting.ScriptProcessor.InstallPackages(IReadOnlyCollection`1 modules, DirectoryPath installPath, PackageType packageType)
   at Cake.Commands.BootstrapCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()
```

**Comment by aabenoja** [comment]
Thank you @stephan7878, I'll see what I can dig up. At a glance it's like the `NuGetPackageInstaller` doesn't handle my package very well.

**Comment by aabenoja** [comment]
@stephan7878 Try again now? You the `#module` directive you provided you should be pulling down a working `v0.20.1-rc3`

**Comment by stephan7878** [comment]
Yes the new version is working for me:

```
PS C:\Repos\Cake> .\build.ps1 --bootstrap -Verbosity Diagnostic
Preparing to run build script...
Running build script...
Verifying assembly 'Cake.Parallel.Module, Version=0.20.0.0, Culture=neutral, PublicKeyToken=null'.
Registering module Cake.Parallel.Module.ParallelCakeModule...
NuGet.config not found.
Analyzing C:/Repos/Cake/build.cake...
Installing modules...
Missing C:\Users\stephanb\.nuget\packages\cake.parallel.module\0.20.1-rc3\cake.parallel.module.0.20.1-rc3.nupkg
  GET https://api.nuget.org/v3/registration3-gz-semver2/cake.parallel.module/index.json
  OK https://api.nuget.org/v3/registration3-gz-semver2/cake.parallel.module/index.json 991ms
Retrieving package 'Cake.Parallel.Module 0.20.1-rc3' from 'nuget.org'.
  GET https://api.nuget.org/v3-flatcontainer/cake.parallel.module/0.20.1-rc3/cake.parallel.module.0.20.1-rc3.nupkg
  OK https://api.nuget.org/v3-flatcontainer/cake.parallel.module/0.20.1-rc3/cake.parallel.module.0.20.1-rc3.nupkg 882ms
Acquiring lock for the installation of Cake.Parallel.Module 0.20.1-rc3
Acquired lock for the installation of Cake.Parallel.Module 0.20.1-rc3
Installing Cake.Parallel.Module 0.20.1-rc3.
Completed installation of Cake.Parallel.Module 0.20.1-rc3
Adding package 'Cake.Parallel.Module.0.20.1-rc3' to folder 'C:\Repos\Cake\tools\Modules'
Added package 'Cake.Parallel.Module.0.20.1-rc3' to folder 'C:\Repos\Cake\tools\Modules'
Added package 'Cake.Parallel.Module.0.20.1-rc3' to folder 'C:\Repos\Cake\tools\Modules' from source 'https://api.nuget.org/v3/index.json'
Successfully installed 'Cake.Parallel.Module 0.20.1-rc3' to C:/Repos/Cake/tools/Modules
Executing nuget actions took 1.2 sec
PS C:\Repos\Cake>
```

**Comment by aabenoja** [comment]
Awesome. I'll release a full `0.20.1` once I resolve some minor build script issues I found while fixing this. Thanks you for the logs.

**Comment by aabenoja** [comment]
For the sake of documenting the root cause at the time of this issue being reported the project was built with `net462`. This may not seem like the issue, especially when [0.20.0](https://www.nuget.org/packages/Cake.Parallel.Module/0.20.0) works perfectly fine when pulled down by other means such as `paket`, but using the `--bootstrap` command exposed an issue in how the module gets "installed."

The primary culprit was the [NuGetContentResolver](https://github.com/cake-build/cake/blob/8e1b9ca261c1713b913905f897d70219a255b99b/src/Cake.NuGet/NuGetContentResolver.cs#L94), primarily where we attempt to find the nearest compatible version available to use. During execution on my windows VM the current version was `net46`. With this project being compiled against `net462` `FrameworkReducer.GetNearest('net46', ['net462'])` would naturally return null, which naturally results in the `failed to install` error being returned just down the stack.

On an interesting note, the error provided by @stephan7878 was a false negative. Yes, it did kill the bootstrap process, but the module was successfully pulled down by nuget all the same. Subsequently running the build results in cake correctly picking up the parallization module and executing it.

At the end of the day the problem has been resolved simply by setting the target framework for this project to `netstandard1.6`. A larger discussion can happen if we want to handle `modules` a little differently in the [ScriptProcessor](https://github.com/cake-build/cake/blob/8e1b9ca261c1713b913905f897d70219a255b99b/src/Cake.Core/Scripting/ScriptProcessor.cs#L203). The biggest hurdle was having to painfully dig deep into the guts of the `NuGetContentResolver` to find that the inability to find a "nearest" framework and we could probably use some better logging in that area to expose this.

cc @gep13
